style: convert tabs to 2 spaces

diff --git a/support/scripts/dotenv-generate b/support/scripts/dotenv-generate
--- a/support/scripts/dotenv-generate
+++ b/support/scripts/dotenv-generate
@@ -1,47 +1,47 @@
 #!/bin/sh
 
 if [ "$1" = "--help" ]; then
-	echo "This script bootstraps a copy of .env using any currently-exported environment variables.
+  echo "This script bootstraps a copy of .env using any currently-exported environment variables.
 
 - To generate a '.envrc' template, pass '--envrc' as the *first* positional argument.
 - To overwrite an existing '.env' file, pass '--force' as the *last* positional argument."
-	exit
+  exit
 fi
 
 project_root=$(dirname "$0")/../../
 cd "$project_root" || exit 1
 
 if [ "$1" = "--envrc" ]; then
-	# generate a .envrc template
-	env_path="$(pwd)/.envrc.local"
+  # generate a .envrc template
+  env_path="$(pwd)/.envrc.local"
 else
-	# generate a .env template
-	env_path="$(pwd)/.env"
+  # generate a .env template
+  env_path="$(pwd)/.env"
 fi
 
 # get last arg
 for last_arg; do true; done
 
 if [ -f "$env_path" ]; then
-	if [ "$last_arg" = "--force" ]; then
-		echo "Overwriting existing file: '$env_path'..."
-	else
-		echo "File already exists: '$env_path'. Aborting..."
-		exit 1
-	fi
+  if [ "$last_arg" = "--force" ]; then
+    echo "Overwriting existing file: '$env_path'..."
+  else
+    echo "File already exists: '$env_path'. Aborting..."
+    exit 1
+  fi
 else
-	echo "Generating local environment: '$env_path'..."
+  echo "Generating local environment: '$env_path'..."
 fi
 
 env_template_path="$(pwd)/support/scripts/dotenv-generate--template"
 output_string="$($env_template_path "$@")"
 
 if [ "$DRY_RUN" = 1 ]; then
-	echo "$output_string"
+  echo "$output_string"
 else
-	# create the .env file
-	echo "$output_string" >"$env_path"
+  # create the .env file
+  echo "$output_string" >"$env_path"
 
-	# set permissions on the newly-created .env file
-	chmod 600 "$env_path"
+  # set permissions on the newly-created .env file
+  chmod 600 "$env_path"
 fi
diff --git a/support/scripts/pre-commit b/support/scripts/pre-commit
--- a/support/scripts/pre-commit
+++ b/support/scripts/pre-commit
@@ -1,7 +1,7 @@
 #!/bin/sh
 
 if [ "$1" = "--help" ]; then
-	echo "Run tasks as part of a git pre-commit workflow.
+  echo "Run tasks as part of a git pre-commit workflow.
 
 A flag must be passed as the that describes the action to be performed.
 
@@ -18,17 +18,17 @@ fi
 cd "$(dirname "$0")/../../" || exit 1
 
 if [ "$1" = "" ]; then
-	echo "A flag must be specified when running this script. Use the '--help' flag for more info."
-	exit 1
+  echo "A flag must be specified when running this script. Use the '--help' flag for more info."
+  exit 1
 elif [ "$1" = "--test-e2e" ]; then
-	echo "Running E2E tests..."
+  echo "Running E2E tests..."
 
-	./support/scripts/test-e2e --quiet --forbid-only --retries 3
-	if [ "$?" != 0 ]; then
-		echo "\033[91m" "One or more E2E tests failed. Aborting the commit..." "\033[39m"
-		exit 1
-	else
-		echo "\033[92m" "E2E tests completed successfully." "\033[39m"
-		exit 0
-	fi
+  ./support/scripts/test-e2e --quiet --forbid-only --retries 3
+  if [ "$?" != 0 ]; then
+    echo "\033[91m" "One or more E2E tests failed. Aborting the commit..." "\033[39m"
+    exit 1
+  else
+    echo "\033[92m" "E2E tests completed successfully." "\033[39m"
+    exit 0
+  fi
 fi
